apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-pod
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: secret-reader
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: my-api-token
          mountPath: /mnt/api-token
          readOnly: true
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: api-token
              key: USERNAME
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-token
              key: PASSWORD
      volumes:
      - name: my-api-token
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: aws-secrets
